apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: day4anapod11
    x: anajenkins
  name: day4anapod11
  namespace: anauska
spec:
  containers:
  - image: anauskadocker1/day4webapp:v1
    name: day4anapod11
    ports:
     - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: day4anasvc
  name: day4anasvc
  namespace: anauska
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    x: anajenkins
  type: NodePort
status:
  loadBalancer: {}
